config/routes.rb
Rails.application.routes.draw do
  
  root to: 'templates#home'
  get '/cursos', to: "templates#cursos"

  namespace :admin do
    resources :alunos, :cursos, :professores
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/curso.rb
class Curso < ApplicationRecord
  belongs_to :professor
end

app/models/professor.rb
class Professor < ApplicationRecord
  has_many :curso
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aluno_params
      params.require(:aluno).permit(:nome, :email, :senha, :cpf, :telefone, :data_nascimento)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :edit, :update, :destroy]

  # GET /cursos
  # GET /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1
  # GET /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: 'Curso was successfully created.' }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: 'Curso was successfully updated.' }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: 'Curso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def curso_params
      params.require(:curso).permit(:titulo, :descricao, :videoIntro, :professor_id)
    end
end

app/controllers/professores_controller.rb
class ProfessoresController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professores
  # GET /professores.json
  def index
    @professores = Professor.all
  end

  # GET /professores/1
  # GET /professores/1.json
  def show
  end

  # GET /professores/new
  def new
    @professor = Professor.new
  end

  # GET /professores/1/edit
  def edit
  end

  # POST /professores
  # POST /professores.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professores/1
  # PATCH/PUT /professores/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professores/1
  # DELETE /professores/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professores_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def professor_params
      params.require(:professor).permit(:nome, :sobre, :foto)
    end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  def home
  end

  def cursos
  end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/professores_helper.rb
module ProfessoresHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno, local: true) do |form| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :data_nascimento %>
    <%= form.date_select :data_nascimento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>




     

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Senha</th>
      <th>Cpf</th>
      <th>Telefone</th>
      <th>Data nascimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.email %></td>
        <td><%= aluno.senha %></td>
        <td><%= aluno.cpf %></td>
        <td><%= aluno.telefone %></td>
        <td><%= aluno.data_nascimento %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @aluno.email %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @aluno.senha %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @aluno.cpf %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @aluno.telefone %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @aluno.data_nascimento %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>

app/views/cursos/_form.html.erb
<%= form_with(model: curso, local: true) do |form| %>
  <% if curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curso.errors.count, "error") %> prohibited this curso from being saved:</h2>

      <ul>
      <% curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :videoIntro %>
    <%= form.text_field :videoIntro %>
  </div>

  <div class="field">
    <%= form.label :professor_id %>
    <%= form.select(:professor_id, Professor.all.collect {|u| [u.nome, u.id]}, :prompt => 'Selecione') %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<h1>Editing Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Show', @curso %> |
<%= link_to 'Back', cursos_path %>

app/views/cursos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cursos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descricao</th>
      <th>Videointro</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td><%= curso.titulo %></td>
        <td><%= curso.descricao %></td>
        <td><%= curso.videoIntro %></td>
        <td><%= curso.professor.nome %></td>
        <td><%= link_to 'Show', curso %></td>
        <td><%= link_to 'Edit', edit_curso_path(curso) %></td>
        <td><%= link_to 'Destroy', curso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curso', new_curso_path %>

app/views/cursos/new.html.erb
<h1>New Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Back', cursos_path %>

app/views/cursos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @curso.titulo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @curso.descricao %>
</p>

<p>
  <strong>Videointro:</strong>
  <%= @curso.videoIntro %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @curso.professor.nome %>
</p>

<%= link_to 'Edit', edit_curso_path(@curso) %> |
<%= link_to 'Back', cursos_path %>

app/views/home/index.html.erb
<%= render "shared/header" %>

<!-- Banner Section -->
<section id="banner">
  <div class="container banner">
    <div class="row">
      <div class="col-md-6 col-sm-6 d-flex align-items-center">
        <div>
          <p class="promo-title">Aprenda a Desenvolver Soluções</p>
          <p>Aprenda gratuitamente com os nossos conteúdos gravados, 
              anote tudo e pague somente para tirar dúvidas em aulas particulares.</p>
          <a data-toggle="modal" data-target="#exampleModal"><img src="./image/play.png" class="play-bnt"> Conheça nosso projeto</a>    
        </div>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="outline: 0;">
                  <span aria-hidden="true" style="color: #fff;">×</span>
                </button>
              </div>
              <div class="modal-body">
                <iframe class="iframe" src="https://www.youtube.com/embed/2GxesFE4ETg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
                </iframe>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-sm-6 text-center">
        <img src="./image/programmer.svg" class="img-fluid img-banner">
      </div>
    </div>
  </div>
  <div class="wave wave1">
  <div class="wave wave2">
  <div class="wave wave3">
  <div class="wave wave4">
  <div class="wave wave5">
  </div></div></div></div></div>
</section>

<main>

<!-- Services Section -->
<section id="services">
  <div class="container">
    <h2 class="title text-center">Sua carreira do Zero ao Profissional</h2>
    <div class="row text-center">
      <div class="col-md-6 services d-flex align-items-center">
        <div>
          <img src="/image/researching.svg" alt="" class="service-img">
          <h5>Desenvolva seu Projeto</h5>
          <div class="content-text">
            <p>Nós oferecemos serviços de qualidade personalizados às necessidades do cliente. 
              Buscando excelência na execução de projetos para a sociedade. Conte conosco e 
              faça seu orçamento.</p>
            <a class="btn" href="/comprar/hora-desenvolvimento">Saiba Mais</a>
          </div>
        </div>
      </div>
      <div class="col-md-6 services d-flex align-items-center">
        <div>
          <img src="/image/community.svg" alt="" class="service-img">
          <h5>Agende uma Reunião</h5>
          <div class="content-text">
            <p>Aqui você pode marcar uma reunião ou consultoria comigo, após marcar irei verificar se o seu pagamento 
                está correto para que possamos dar os próximos passos, vejo você em nossa reunião !!!</p>
            <a class="btn" href="/agenda">Saiba Mais</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <img src="./image/wave.png" alt="" class="bottom-img">
</section> 
     



<%= render "shared/cursos" %>
  

<!-- Linea Section -->
<section id="linea">
  <div class="container-fluid linea"></div>
</section>

<%= render "shared/comunidade" %>
<%= render "shared/comentario" %>
<%= render "shared/produtos" %>
<%= render "shared/footer" %>


     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plataforma TorneSe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript,Node.js,C#,Ruby,Java,Asp,PHP,Wordpress,Aplicativos">
    <meta name="author" content="Danilo Aparecido dos Santos">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width,user-scalable=no">

    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:site" content="@didox">
    <meta property="twitter:title" content="Torne-se um Programador | Aprenda a Desenvolver Soluções">
    <meta property="twitter:description" content="Com ele você irá aprender tudo que precisa para se tornar um programador.">
    <meta property="twitter:image" content="http://www.torneseumprogramador.com.br/imagens/imggrath.png">

    <meta property="og:site_name" content="Torne-se um Programador | Aprenda a Desenvolver Soluções">
    <meta property="og:title" content="<% if @titulo.present? %><%= @titulo %><% else %> Torne-se um Programador <% end %>">
    <meta property="og:type" content="website">
    <meta property="og:url" content="<% if @titulo.present? %><%= @titulo %><% else %> Torne-se um Programador <% end %>">
    <meta property="og:image" content="<% if @titulo.present? %><%= @titulo %><% else %> Torne-se um Programador <% end %>">
    <meta property="og:description" content="<% if @titulo.present? %><%= @titulo %><% else %> Torne-se um Programador <% end %>">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nixie+One&display=swap" >
    <!-- File slick -->
    <link rel="stylesheet" type="text/css" href="slick/slick.css">
    <link rel="stylesheet" type="text/css" href="slick/slick-theme.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>

  <!-- Global site tag (gtag.js) - Google Ads: 939847686 -->
<script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
<script src="slick/slick.js" type="text/javascript" charset="utf-8"></script>
<script defer src="icons/js/all.js"></script>
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-939847686"></script>
<script src="javascript/googleAds.js"></script>
<noscript>
  <img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=504690253632854&ev=PageView&noscript=1"/>
</noscript>
<!-- End Facebook Pixel Code -->

<!-- Hotjar Tracking Code for http://www.torneseumprogramador.com.br/ -->
<script>
  (function(h,o,t,j,a,r){
      h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
      h._hjSettings={hjid:1893193,hjsv:6};
      a=o.getElementsByTagName('head')[0];
      r=o.createElement('script');r.async=1;
      r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
      a.appendChild(r);
  })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

<!-- Facebook Pixel Code -->
<script>
  ! function(f, b, e, v, n, t, s) {
    if (f.fbq) return;
    n = f.fbq = function() {
        n.callMethod ?
            n.callMethod.apply(n, arguments) : n.queue.push(arguments)
    };
    if (!f._fbq) f._fbq = n;
    n.push = n;
    n.loaded = !0;
    n.version = '2.0';
    n.queue = [];
    t = b.createElement(e);
    t.async = !0;
    t.src = v;
    s = b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t, s)
}(window, document, 'script',
    'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '504690253632854');
fbq('track', 'PageView');
</script>
<noscript>
  <img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=504690253632854&ev=PageView&noscript=1"/>
</noscript>
<!-- End Facebook Pixel Code -->


  <!-- Global Site Tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-70181827-1"></script>
  <script src="javascript/googleAnalytics.js"></script>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS --> 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous">
  </script>

  <script>
    $(document).on('ready', function() {
      $(".regular").slick({
          dots: true,
          infinite: true,
          slidesToShow: 3,
          slidesToScroll: 1
      });
    });
  </script> 
</html>

app/views/professores/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :sobre %>
    <%= form.text_field :sobre %>
  </div>

  <div class="field">
    <%= form.label :foto %>
    <%= form.text_field :foto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professores/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professores_path %>

app/views/professores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sobre</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professores.each do |professor| %>
      <tr>
        <td><%= professor.nome %></td>
        <td><%= professor.sobre %></td>
        <td><%= professor.foto %></td>
        <td><%= link_to 'Show', professor %></td>
        <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
        <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professor', new_professor_path %>

app/views/professores/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professores_path %>

app/views/professores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @professor.nome %>
</p>

<p>
  <strong>Sobre:</strong>
  <%= @professor.sobre %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @professor.foto %>
</p>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professores_path %>

app/views/shared/_comunidade.html.erb
<!-- Banner-Community Section -->
<section id="banner-community">
  <div class="container banner-community">
    <div class="row">
      <div class="col-md-6 col-sm-6 d-flex align-items-center">
        <div>
          <p class="promo-title">Comunidade dos Programadores </p>
          <p>Aprender a programar, a desenvolver, a planejar seus projetos para gerar resultados faz muito sentido. Mas também é preciso 
              conquistar clientes e aqui você também aprende a empreender seu negócio.</p>
          <a class="btn" href="http://cursos.torneseumprogramador.com.br/?ref=O25447624Q" target="_blanck">Conheça nossa Comunidade</a> 
        </div>
      </div>
      <br>
      <div class="col-md-6 col-sm-6 div-img-community text-center">
        <img src="/image/group_chat.svg" class="img-fluid img-banner-community">
      </div>
    </div>
  </div>
</section>

app/views/templates/cursos.html.erb
<%= render "shared/header" %>
<%= render "shared/cursos" %>
  

<!-- Linea Section -->
<section id="linea">
  <div class="container-fluid linea"></div>
</section>

<%= render "shared/comunidade" %>
<%= render "shared/produtos" %>
<%= render "shared/footer" %>